services:
  app:
    image: hello-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3210:3000
    environment: 
      - REDIS_URL=//localhost:6378
      - MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database
    container_name: hello-front-dev # This will name the container hello-front-dev
  debug-helper:
    image: busybox
 nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy